# Generated by Django 3.1 on 2020-09-09 14:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryentry',
            name='critter_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
