# Generated by Django 3.1 on 2020-09-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='critter_request',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='request_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
