# Generated by Django 3.1 on 2020-09-09 14:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20200907_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='request_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
